#Independent settings for the planner's costmap

global_costmap:
  #Set the global and robot frames for the costmap
  global_frame: /map
  #global_frame: /odom
  robot_base_frame: base_link

  #Set the update and publish frequency of the costmap
  update_frequency: 3.0
  publish_frequency: 2.0

  #We'll use a map served by the gmapping to initialize this costmap
  static_map: true
  rolling_window: false

  footprint_padding: 0.05

  width: 20.0
  height: 20.0
  resolution: 0.05
