TebLocalPlannerROS:
  # Robot Configuration Parameters
  acc_lim_x: 0.1
  acc_lim_theta: 0.1
  min_obstacle_dist: 0.1
  max_vel_x: 0.3
  max_vel_x_backwards: 0.1
  max_vel_theta: 0.3
  min_turning_radius: 0.0
  wheelbase: 1.0
  cmd_angle_instead_rotvel: false
  weight_max_vel_x: 2
  weight_max_vel_theta: 1
  weight_acc_lim_x: 1
  weight_acc_lim_theta: 1
  weight_kinematics_forward_drive: 1
  penalty_epsilon: 0.05

  #publish_feedback: true
  map_frame: "/navigation/map"
  odom_topic: "/base/odom"
  footprint_model: # types: "point", "circular", "line", "two_circles", "polygon"
   type: "circular"
   radius: 0.26 # for type "circular"
  #line_start: [-0.3, 0.0] # for type "line"
  #line_end: [0.3, 0.0] # for type "line"
  #front_offset: 0.2 # for type "two_circls"
  #front_radius: 0.2 # for type "two_circles"
  #rear_offset: 0.2 # for type "two_circles"
  #rear_radius: 0.2 # for type "two_circles"
  #vertices: [ [0.25, -0.05], [0.18, -0.05], [0.18, -0.18], [-0.19, -0.18], [-0.25, 0], [-0.19, 0.18], [0.18, 0.18], [0.18, 0.05], [0.25, 0.05] ] # for type "polygon"
